###
POST http://localhost:9000/api/v1/libros HTTP/1.1
Content-Type: application/json

{
  "titulo": "Cien años de soledad",
  "autor": "Gabriel García Márquez",
  "genero": "Realismo mágico",
  "anioPublicacion": 1967
}

###
GET http://localhost:9000/api/v1/libros HTTP/1.1

###
GET http://localhost:9000/api/v1/libros/68fffb657d4e0dfc9de5ac0d HTTP/1.1

###
DELETE http://localhost:9000/api/v1/libros/68fffb487d4e0dfc9de5ac0b HTTP/1.1

###
PUT http://localhost:9000/api/v1/libros/68fffb487d4e0dfc9de5ac0b HTTP/1.1
Content-Type: application/json

{
  "titulo": "El amor en los tiempos del cólera",
  "autor": "Gabriel García Márquez",
  "genero": "Romance",
  "anioPublicacion": 1985
}